import { Gallery } from '../models/gallery';

/**
 * Gallery seed data — the real festival photographs in `src/assets/images/`.
 *
 * Every entry below points at a file that actually exists; nothing here is a
 * placeholder. Categories were assigned from the content of each photograph:
 * the idol itself, puja and offerings, the pandal and its archway, the people
 * who run the mandap, and the nimarjanam procession.
 *
 * To publish more photos: drop the files into `src/assets/images/` and add an
 * entry here. The grid, filters, lightbox and home-page preview all read from
 * this array.
 */
export const MOCK_GALLERY: Gallery[] = [
  // ---------------------------------------------------------------- Ganesh
  {
    galleryId: 1,
    title: 'Shree Ganesh at the Mandap',
    description: 'The idol seated on the peacock throne, garlanded for darshan.',
    imageUrl: 'assets/images/IMG_20250905_123805.jpg',
    category: 'Ganesh',
    displayOrder: 1,
    isActive: true,
    featured: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 2,
    title: 'Darshan by Lamplight',
    description: 'The idol lit for the evening darshan.',
    imageUrl: 'assets/images/IMG_20250906_190113.jpg',
    category: 'Ganesh',
    displayOrder: 2,
    isActive: true,
    featured: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 3,
    title: 'Crowned in Gold',
    description: 'A closer look at the crown and the jewelled headpiece.',
    imageUrl: 'assets/images/IMG_20250905_123719.jpg',
    category: 'Ganesh',
    displayOrder: 3,
    isActive: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 4,
    title: 'The Divine Face',
    description: 'Detail of the idol beneath the canopy of the throne.',
    imageUrl: 'assets/images/IMG_20250905_123705.jpg',
    category: 'Ganesh',
    displayOrder: 4,
    isActive: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 5,
    title: 'Garlanded for the Day',
    description: 'Fresh flower garlands offered at the morning darshan.',
    imageUrl: 'assets/images/IMG_20250905_123653.jpg',
    category: 'Ganesh',
    displayOrder: 5,
    isActive: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 6,
    title: 'Beneath Shree Vishnu',
    description: 'The idol framed by the carved backrest of the throne.',
    imageUrl: 'assets/images/IMG_20250905_123743.jpg',
    category: 'Ganesh',
    displayOrder: 6,
    isActive: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 7,
    title: 'Evening Glow',
    description: 'The idol after nightfall, before the pandal closes.',
    imageUrl: 'assets/images/IMG_20250903_205853.jpg',
    category: 'Ganesh',
    displayOrder: 7,
    isActive: true,
    createdDate: '2025-09-03',
  },
  {
    galleryId: 8,
    title: 'Peacock Throne',
    description: 'The idol seated in full, seen from the mandap floor.',
    imageUrl: 'assets/images/IMG_20250902_143311.jpg',
    category: 'Ganesh',
    displayOrder: 8,
    isActive: true,
    createdDate: '2025-09-02',
  },
  {
    galleryId: 9,
    title: 'Under the Open Sky',
    description: 'The idol outside the pandal on a clear afternoon.',
    imageUrl: 'assets/images/IMG_20250906_124917.jpg',
    category: 'Ganesh',
    displayOrder: 9,
    isActive: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 10,
    title: 'Ganesh on the Swan',
    description: 'An earlier year at the mandap — the idol seated on a swan.',
    imageUrl: 'assets/images/IMG_20240916_113705.jpg',
    category: 'Ganesh',
    displayOrder: 10,
    isActive: true,
    createdDate: '2024-09-16',
  },
  {
    galleryId: 11,
    title: 'The Swan Vahana',
    description: 'The full swan idol under the white pandal.',
    imageUrl: 'assets/images/IMG_20240916_131419.jpg',
    category: 'Ganesh',
    displayOrder: 11,
    isActive: true,
    createdDate: '2024-09-16',
  },

  // ------------------------------------------------------------------ Puja
  {
    galleryId: 12,
    title: 'Ganga Harathi',
    description: 'The evening harathi performed with lamps and incense.',
    imageUrl: 'assets/images/ganaga harti.jpg',
    category: 'Puja',
    displayOrder: 12,
    isActive: true,
    featured: true,
    createdDate: '2025-09-01',
  },
  {
    galleryId: 13,
    title: 'Offerings at the Idol',
    description: 'The puja thali and offerings laid out before the idol.',
    imageUrl: 'assets/images/IMG_20250906_124904.jpg',
    category: 'Puja',
    displayOrder: 13,
    isActive: true,
    featured: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 14,
    title: 'The Pandal Prepared',
    description: 'The stage set with offerings ahead of the day’s puja.',
    imageUrl: 'assets/images/IMG_20250903_153924.jpg',
    category: 'Puja',
    displayOrder: 14,
    isActive: true,
    createdDate: '2025-09-03',
  },
  {
    galleryId: 15,
    title: 'Ready for Darshan',
    description: 'The idol on the blue platform, garlands and lamps in place.',
    imageUrl: 'assets/images/IMG_20250903_153615.jpg',
    category: 'Puja',
    displayOrder: 15,
    isActive: true,
    createdDate: '2025-09-03',
  },
  {
    galleryId: 16,
    title: 'Devotees at the Pandal',
    description: 'Families gathered on the mandap floor for darshan.',
    imageUrl: 'assets/images/IMG_20240914_204233.jpg',
    category: 'Puja',
    displayOrder: 16,
    isActive: true,
    createdDate: '2024-09-14',
  },

  // ----------------------------------------------------------- Decorations
  {
    galleryId: 17,
    title: 'The Mandap Archway',
    description:
      'The Akhuratha Mandap entrance lit up at night, with every festival year on the arch.',
    imageUrl: 'assets/images/IMG_20250901_210152.jpg',
    category: 'Decorations',
    displayOrder: 17,
    isActive: true,
    featured: true,
    createdDate: '2025-09-01',
  },
  {
    galleryId: 18,
    title: 'Welcome to the Mandap',
    description: 'The archway by day, with the saffron flag above the entrance.',
    imageUrl: 'assets/images/IMG_20240914_210037.jpg',
    category: 'Decorations',
    displayOrder: 18,
    isActive: true,
    createdDate: '2024-09-14',
  },
  {
    galleryId: 19,
    title: 'Drapes and Leaf Garlands',
    description: 'Mango-leaf torans strung across the white pandal drapes.',
    imageUrl: 'assets/images/IMG_20250903_153851.jpg',
    category: 'Decorations',
    displayOrder: 19,
    isActive: true,
    createdDate: '2025-09-03',
  },
  {
    galleryId: 20,
    title: 'Years on the Arch',
    description: 'The mandap stage framed by the year panels of past festivals.',
    imageUrl: 'assets/images/IMG_20250903_153624.jpg',
    category: 'Decorations',
    displayOrder: 20,
    isActive: true,
    createdDate: '2025-09-03',
  },

  // ------------------------------------------------------------ Volunteers
  {
    galleryId: 21,
    title: 'Raising the Pandal',
    description: 'Volunteers on the scaffolding as the pandal goes up around the idol.',
    imageUrl: 'assets/images/IMG_20250906_143655.jpg',
    category: 'Volunteers',
    displayOrder: 21,
    isActive: true,
    featured: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 22,
    title: 'The Mandap Team',
    description: 'The people who organise the festival, at the pandal.',
    imageUrl: 'assets/images/IMG_20250906_002957.jpg',
    category: 'Volunteers',
    displayOrder: 22,
    isActive: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 23,
    title: 'A Moment of Darshan',
    description: 'A devotee pauses before the idol during the evening.',
    imageUrl: 'assets/images/IMG_20250905_223932.jpg',
    category: 'Volunteers',
    displayOrder: 23,
    isActive: true,
    createdDate: '2025-09-05',
  },
  {
    galleryId: 24,
    title: 'Little Hands Folded',
    description: 'A child offers his prayers at the mandap.',
    imageUrl: 'assets/images/IMG_20240917_004502.jpg',
    category: 'Volunteers',
    displayOrder: 24,
    isActive: true,
    createdDate: '2024-09-17',
  },

  // ------------------------------------------------------------ Procession
  {
    galleryId: 25,
    title: 'Nimarjanam Procession',
    description: 'The idol on its float, moving through the streets after dark.',
    imageUrl: 'assets/images/IMG_20250907_044558.jpg',
    category: 'Procession',
    displayOrder: 25,
    isActive: true,
    featured: true,
    createdDate: '2025-09-07',
  },
  {
    galleryId: 26,
    title: 'Loading for the Journey',
    description: 'The idol secured on the trailer before the procession sets off.',
    imageUrl: 'assets/images/IMG_20250906_205449.jpg',
    category: 'Procession',
    displayOrder: 26,
    isActive: true,
    createdDate: '2025-09-06',
  },
  {
    galleryId: 27,
    title: 'Leaving the Mandap',
    description: 'The idol out on the street on the final day of the festival.',
    imageUrl: 'assets/images/IMG_20240917_142439.jpg',
    category: 'Procession',
    displayOrder: 27,
    isActive: true,
    createdDate: '2024-09-17',
  },
  {
    galleryId: 28,
    title: 'Farewell Under Blue Sky',
    description: 'Ganpati Bappa Morya — the idol on its way to visarjan.',
    imageUrl: 'assets/images/IMG_20240917_162305.jpg',
    category: 'Procession',
    displayOrder: 28,
    isActive: true,
    createdDate: '2024-09-17',
  },
];
