import { Competition, Game, KidsContent, Quiz, QuizQuestion } from '../models/kids.model';

const iso = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();

export const MOCK_KIDS_CONTENT: KidsContent[] = [
  {
    id: 1,
    contentType: 'Bhajan',
    title: 'Sukhkarta Dukhharta',
    shortDescription: 'The classic Marathi aarti of Shree Ganesh.',
    description: 'Traditional aarti sung during the morning and evening puja.',
    singer: 'Mandap Bhajan Group',
    thumbnailPath: 'images/gallery/ganesh-2.jpg',
    mediaPath: null,
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ageGroup: 'All',
    duration: '3:20',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
    createdDate: iso(20),
  },
  {
    id: 2,
    contentType: 'Mantra',
    title: 'Vakratunda Mahakaya',
    shortDescription: 'The Ganesh dhyana mantra.',
    description: 'Recited before beginning any auspicious work.',
    singer: null,
    thumbnailPath: 'images/gallery/ganesh-1.jpg',
    mediaPath: null,
    videoUrl: null,
    ageGroup: 'All',
    duration: '0:40',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
    createdDate: iso(19),
  },
  {
    id: 3,
    contentType: 'Story',
    title: 'How Ganesha Got His Elephant Head',
    shortDescription: 'A favourite story for young devotees.',
    description: 'The well-loved tale of Parvati, Shiva and little Ganesha.',
    singer: null,
    thumbnailPath: 'images/gallery/ganesh-3.jpg',
    mediaPath: null,
    videoUrl: null,
    ageGroup: '5-10',
    duration: '5:00',
    displayOrder: 1,
    isFeatured: false,
    isActive: true,
    createdDate: iso(15),
  },
  {
    id: 4,
    contentType: 'Rhyme',
    title: 'Ganpati Bappa Morya',
    shortDescription: 'A cheerful rhyme for the little ones.',
    description: 'Sing along rhyme for the festival.',
    singer: 'Kids Choir',
    thumbnailPath: 'images/gallery/ganesh-6.jpg',
    mediaPath: null,
    videoUrl: null,
    ageGroup: '3-7',
    duration: '2:10',
    displayOrder: 1,
    isFeatured: false,
    isActive: true,
    createdDate: iso(12),
  },
];

export const MOCK_KIDS_QUIZZES: Quiz[] = [
  {
    id: 1,
    title: 'Ganesha Basics',
    description: 'Simple questions about Shree Ganesh for beginners.',
    level: 'Easy',
    thumbnailPath: 'images/gallery/ganesh-1.jpg',
    timeLimitSeconds: 180,
    passingPercentage: 50,
    certificatePercentage: 80,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'Festival Traditions',
    description: 'Questions about Ganeshotsav customs and rituals.',
    level: 'Medium',
    thumbnailPath: 'images/gallery/ganesh-4.jpg',
    timeLimitSeconds: 240,
    passingPercentage: 60,
    certificatePercentage: 85,
    displayOrder: 2,
    isActive: true,
  },
];

export const MOCK_KIDS_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    quizId: 1,
    question: 'What does Ganesha ride as his vehicle (vahana)?',
    explanation: 'Ganesha rides Mooshak, the mouse.',
    points: 1,
    displayOrder: 1,
    isActive: true,
    options: [
      { id: 1, questionId: 1, optionText: 'A mouse', imagePath: null, isCorrect: true, displayOrder: 1, isActive: true },
      { id: 2, questionId: 1, optionText: 'A peacock', imagePath: null, isCorrect: false, displayOrder: 2, isActive: true },
      { id: 3, questionId: 1, optionText: 'A lion', imagePath: null, isCorrect: false, displayOrder: 3, isActive: true },
      { id: 4, questionId: 1, optionText: 'An owl', imagePath: null, isCorrect: false, displayOrder: 4, isActive: true },
    ],
  },
  {
    id: 2,
    quizId: 1,
    question: 'Which sweet is Ganesha most fond of?',
    explanation: 'Modak is his favourite sweet.',
    points: 1,
    displayOrder: 2,
    isActive: true,
    options: [
      { id: 5, questionId: 2, optionText: 'Modak', imagePath: null, isCorrect: true, displayOrder: 1, isActive: true },
      { id: 6, questionId: 2, optionText: 'Jalebi', imagePath: null, isCorrect: false, displayOrder: 2, isActive: true },
      { id: 7, questionId: 2, optionText: 'Barfi', imagePath: null, isCorrect: false, displayOrder: 3, isActive: true },
      { id: 8, questionId: 2, optionText: 'Ladoo', imagePath: null, isCorrect: false, displayOrder: 4, isActive: true },
    ],
  },
];

const YEAR = new Date().getFullYear();

export const MOCK_KIDS_COMPETITIONS: Competition[] = [
  {
    id: 1,
    title: 'Drawing Competition',
    description: 'Theme-based drawing competition for three age groups.',
    year: YEAR,
    thumbnailPath: 'images/competitions/competition-1.jpg',
    registrationStartDate: iso(10),
    registrationEndDate: iso(-3),
    startDate: iso(-7),
    endDate: iso(-7),
    maxParticipants: 60,
    displayOrder: 1,
    isActive: true,
    isRegistrationOpen: true,
  },
  {
    id: 2,
    title: 'Fancy Dress Competition',
    description: 'Dress up as your favourite deity or freedom fighter.',
    year: YEAR,
    thumbnailPath: 'images/competitions/competition-2.jpg',
    registrationStartDate: iso(10),
    registrationEndDate: iso(-2),
    startDate: iso(-6),
    endDate: iso(-6),
    maxParticipants: 40,
    displayOrder: 2,
    isActive: true,
    isRegistrationOpen: true,
  },
];

export const MOCK_KIDS_GAMES: Game[] = [
  {
    id: 1,
    title: 'Ganesh Memory Match',
    description: 'Flip the cards and match the festival pairs.',
    gameType: 'Memory',
    difficulty: 'Easy',
    thumbnailPath: 'images/competitions/competition-3.jpg',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'Festival Word Search',
    description: 'Find all the hidden festival words.',
    gameType: 'WordSearch',
    difficulty: 'Medium',
    thumbnailPath: 'images/competitions/competition-4.jpg',
    displayOrder: 2,
    isActive: true,
  },
];
